resources:
  - name: gociexampleGithubRepo
    type: GitRepo
    configuration:
      gitProvider: zen1
      path: aaragorn2/jfrog-pipelines-jenkins-example
  - name: jenkinsBuildInfo
    type: BuildInfo
    configuration:
      sourceArtifactory: PartnershipArtifactory
      buildName: goci-example/master
      buildNumber: 1
      externalCI: jenkins_openshiftk8s_com
  - name: releaseBuildInfo
    type: BuildInfo
    configuration:
      sourceArtifactory: PartnershipArtifactory
      buildName: goci-example/master
      buildNumber: 1
